import random
pivas = [
'Лакинское',
'Первый Тайм(Брянск)',
'Жигулевское(Лакинск)',
'Московское',
'Жигулевское(Брянск)',
'Жигулевское Воронеж',
'Русский Лагер',
'Вятич Ячменное',
'Старовар Жигулевское',
'Чешский Лежак',
'Немецкий Пилснер',
'Вятич Бочковое',
'Чешское светлое',
'Немецкое',
'Вятич Элитное',
'Вятич Рижское',
'Чешское оригинальное',
'Трое в лодке',
'Курская дуга',
'Сибирский пивовар',
'Пилснер',
'Крюгер Классическое',
'Крюгер золотое',
'Два Путя',
'Apres-Ski Pils',
'Gambrinus Premium',
'Einsiedler Klausner Pils',
'Carling Original Lager',
'Zubr Gold',
'Budweiser Budvar',
'Weltenburger Pils',
'Campus Premium',
'Pilsner Urquell',
'Gaffel Kolsch',
'Spaten',
'Guinness Hop House 13 Lager',
'Fullers London Pride',
'Fullers Organic Honey Dew(Blond Ale)',
'Tripel Karmeliet',
'Вятич Нефильтрованное',
'Чешское Н/Ф',
'Schwarzkaiser Classic Pilsner',
'Quicksort',
'Три Дня. Вестфальское',
'Schneider TAP5 Meine Hopfenweisse',
'Wooha Hop Pinata IPA',
'La Trappe Blond(Belgian Ale)',
'Huyghe Averbode Abbaye',
'Schneider TAP 7',
'Темная Башня',
'Красный Вельвет',
'Алтайское Бархатное',
'Старовар Черное',
'Ирландский эль',
'Крюгер бархатное',
'Litovel Dark',
'Weihenstephaner Tradition Bayrisch Dunkel',
'Bernard Cerna Lavina',
'Staropramen Velvet',
'O-Hara-s Irish Stout',
'St.Peter-s Cream Stout',
'St.Peter-s Plum Porter',
'Leffe Brune',
'Petrus Aged Red',
'Gulden Draak',
'Huyghe Delirium Nocturnum',
'Kilkenny Draught',
'Guinness Draught',
'Pohjala Must Kuld',
'Пшеничное Мягкое(Брянск)',
'Баварский Характер',
'Mazaй',
'Особое поручение',
'Эммер Бланш',
'Varka Psheno',
'Вайс Берг',
'Хамовники Пшеничное',
'Einsiedler Weissbier',
'Weihenstephaner Hefe-Weissbier',
'Erdinger Weissbier',
'Limburgse Witte',
'Schneider TAP4 Meine Festweisse',
'Van Steenberge Baptist Wit',
'Hoegaarden',
'Mort Subite Witte',
'Ayinger Urweisse',
'Медовуха',
'Schöfferhofer Grapefruit',
'Mort Subite Kriek',
'Kriek Boon Lambic',
'Bockor Kriek Max',
'Barbe Ruby',
'Huyghe Delirium Red',
'Lindemans Pecheresse',
'Пятый Океан IPA',
'Panzer Mikhail',
'Beer Bros Brewery Smart Admin(APA)',
'Konix IPA Overfall',
'XP Brewery Minimax(APA)',
'XP Brewery Hyperplane',
'Panzer Starlight(APA)',
'Landau Beerlab Тотальное обнуление(West coast IPA)',
'Beer Bros Mango Mayhem(IPA)',
'Black Head WTF(APA)',
'Plan B Солнечный ветер(APA)',
'Волковская Пивоварня Sliva',
'Chibis Avenue 77 Simcoe - Mosaic(American IPA)',
'Konix Milk Shake Peach',
'Beer Bros Heavy Gratefulness(DIPA)',
'Panzer Акварель(IPA)',
'Panzer Super Mango(APA)',
'Salden-S MilkShake Coconut - Ice-Cream Dipa',
'Landau Beerlab Sabro Lake',
'Salden-S MilkShake Mango DIPA',
'Plan B Отличный План',
'Pivot Point БАНАНБЕRRИ Apricot(Milkshake IPA)',
'Plan B Ковбой Мальборо',
'Alaska Метаморфозы(Milkshake Fruit DIPA)',
'Black Head Крепкая Парочка(DIPA)',
'Coven Aura',
'Бакунин Fibonacci(DIPA)',
'Plan B Tropical Painkiller',
'Palchevskiy - Wolf-s Crossover(DIPA)',
'Af Brew Mosaic(IPA)',
'Joker IPA',
'Af Brew Ingria(IPA)',
'Pivot Point Ёлы-Палы(Triple IPA)',
'Brewdog Hazy Jane 5.0',
'Brewdog Duopolis',
'Kona Big Wave Golden Ale',
'Mikkeller Side Eyes Pale Ale',
'Brewdog Dead Pony Club',
'Jaws Populism Mosaic Edition(NEIPA)',
'Brewdog Elvis Juice',
'Sweet Water IPA',
'Sweet Water 420 Strain G13(New England IPA)',
'Pivot Point Белка, Я Люблю Тебя',
'G - B Вишня в Шоколаде(Stout)',
'Konix Black Illusion(Milk Stout)',
'Salden-S Sweet Stout Cola',
'Alaska Стаутский Советник',
'Selfmade Cocoa Chaos(Imperial Stout)',
'Trigger RIS',
'XP Brewery Tetrahymena(English Barleywine)',
'XP Brewery MindBug(RIS)',
'Konix RIS Barrel  # Виски',
'Jaws Holiness(Quadrupel)',
'Af Brew Popcorn Pimp(Imperial Stout)',
'Atmosphere Тропическая Дичь 2.0 Pineapple - Passion Fruit Sour Ale',
'XP Brewery Mango - Raspberry',
'Coven Last Resort(Tomato Gose)',
'Landau Beerlab Hard Seltzer Lemon - Lime(Sour Ale)',
'L - K Pizza Gose',
'LaBEERint Sour Kiwi Pinapple',
'Brewlok Rusalka Raspberry Sour Ale',
'Panzer Catch Up! Tomato Gose',
'Atmosphere Exotic',
'Alaska Фейхоа(Sour Ale)',
'Zavod Bloody Mary v2.0 (Gose)',
'Salden-S Tomato Gose',
'Jaws Berry Mary Cranberry(Berliner Weisse)',
'Бакунин Funky Fresh',
'Jaws Sour Breeze Mango',
'Big Village Hyperrealism(Imperial Gose)',
'Af Brew Raspberry is my Sanctuary(Berliner Weisse)',
'Af Brew Kiss the Dust! DDH Citra+Mosaic(Sour IPA)',
'Af Brew It-s Over 9000 Mango/Pineapple/Lime',
'Af Brew It-s Over 9000! Raspberry/Cherry/Lime',
'Jaws Ищу Человека White Edition',
'XP Brewery Average Bear',
'St.Anton Сидр п/сух.',
'Trigger Сидр вишневый полусухой',
'Coven Ich Will(Hoppy Lager)',
'Brewlok Kikimora(Milk Stout)',
'Konix Very Happy Cider',
'Konix Hefeweizen Banana',
'Волковская Пивоварня Hoppy Cider',
'Plan B Бэрримор Овсяный Стаут',
'Brewlok Koshey(Pepper Stout)',
'Trigger Сидр Aperol Spritz',
'N.Rigas White Moon(Stout)',
'Бакунин Рука Бога(Uncommon Golden Ale)',
'Wychwood Hobgoblin Gold',
'Бакунин Нуар',
'Konix Brewery Cherry Ruby(Fruit Beer)',
'Brewdog Pale Ale',
'Af Brew Redneck Ale(Pumpkin Ale)',
'Сидр Келвиш',
'Lilley-s Cider Mango',
'Lilley-s Cider Cherries - Berries',
'Alska Strawberry - Lime',
'Cidre Celtic Marches Abrahalls AD',
'Вятский Квас',
'Лимонад Бочкари'
]


piv4 = {'Лакинское': ('4.7', '109rub'), 
        'Первый Тайм (Брянск)': ('3.8', '109rub'), 
        'Жигулевское (Лакинск)': ('4.0', '114rub'), 
        'Московское': ('5.0', '118rub'), 
        'Жигулевское (Брянск)': ('4.5', '126rub'), 
        'Жигулевское Воронеж': ('4.3', '133rub'), 'Русский Лагер': ('4.0', '133rub'), 
        'Вятич Ячменное': ('4.5', '135rub'), 'Старовар Жигулевское': ('4.2', '144rub'), 
        'Чешский Лежак': ('4.3', '149rub'), 'Немецкий Пилснер': ('4.8', '155rub'), 'Вятич Бочковое': ('4.5', '158rub'), 'Чешское светлое': ('4.6', '159rub'), 
        'Немецкое':('4.2', '165rub'), 'Вятич Элитное': ('5.4', '167rub'), 
        'Вятич Рижское': ('4.9', '167rub'), 'Чешское оригинальное': ('4.7', '169rub'), 'Трое в лодке': ('4.9', '175rub'), 'Курская дуга': ('4.0', '175rub'), 'Сибирский пивовар': ('4.9', '175rub'), 'Пилснер 34/70': ('4.5', '186rub'), 'Крюгер Классическое': ('5.0', '187rub'), 'Крюгер золотое': ('6.5', '189rub'), 'Два Путя': ('4.5', '194rub'), 'Apres-Ski Pils': ('4.7', '200rub'), 'Gambrinus Premium': ('5.2', '275rub'), 'Einsiedler Klausner Pils': ('4.9', '284rub'), 'Carling Original Lager': ('4.0', '285rub'), 'Zubr Gold': ('4.6', '295rub'), 'Budweiser Budvar': ('5.0', '298rub'), 'Weltenburger Pils': ('4.9', '300rub'), 'Campus Premium': ('5.0', '315rub'), 'Pilsner Urquell': ('4.4', '325rub'), 'Gaffel Kolsch ': ('5.2', '325rub'), 'Spaten': ('5.2', '360rub'), 'Guinness Hop House 13 Lager': ('5.0', '365rub'), 'Fullers London Pride': ('4.7', '370rub'), 'Fullers Organic Honey Dew (Blond Ale)': ('5.0', '375rub'), 'Tripel Karmeliet': ('8.4', '450rub'), 'Вятич Нефильтрованное': ('4.9', '158rub'), 'Вятич 31 День "Зеленое"': ('5.9', '162rub'), 'Чешское Н/Ф': ('4.7', '169rub'), 'Schwarzkaiser Classic Pilsner': ('4.5', '175rub'), 'Quicksort': ('5.0', '184rub'), 'Три Дня. Вестфальское': ('4.7', '250rub'), 'Schneider TAP5 Meine Hopfenweisse': ('8.2', '340rub'), 'Wooha Hop Pinata IPA': ('6.2', '380rub'), 'La Trappe Blond(Belgian Ale)': ('6.5', '415rub'), 'Huyghe Averbode Abbaye': ('7.5', '465rub'), 'Schneider TAP 7': ('5.4', '490rub'), 'Темная Башня': ('4.5', '137rub'), 'Красный Вельвет': ('4.5', '142rub'), 'Алтайское Бархатное': ('4.5', '156rub'), 'Старовар Черное': ('4.9', '162rub'), 'Ирландский эль': ('6.7', '173rub'), 'Крюгер бархатное': ('4.1', '189rub'), 'Litovel Dark ': ('3.8', '290rub'), 'Weihenstephaner Tradition Bayrisch Dunkel': ('5.2', '296rub'), 'Bernard Cerna Lavina': ('5.1', '298rub'), 'Staropramen Velvet ': ('5.1', '330rub'), "O'Hara's Irish Stout ": ('4.3', '370rub'), "St.Peter's Cream Stout": ('6.5', '370rub'), "St.Peter's Plum Porter": ('5.0', '380rub'), 'Leffe Brune ': ('6.5', '395rub'), 'Petrus Aged Red ': ('8.5', '452rub'), 'Gulden Draak ': ('10.5', '460rub'), 'Huyghe Delirium Nocturnum': ('8.5', '475rub'), 'Kilkenny Draught': ('4.3', '515rub'), 'Guinness Draught': ('4.2', '550rub'), 'Pohjala Must Kuld': ('7.8', '655rub'), 'Пшеничное Мягкое(Брянск)': ('4.5', '137rub'), 'Баварский Характер': ('5.5', '144rub'), 'Mazaй': ('4.8', '160rub'), 'Особое поручение': ('5.0', '166rub'), 'Эммер Бланш': ('4.5', '174rub'), 'Varka Psheno': ('4.5', '175rub'), 'Вайс Берг': ('4.7', '179rub'), 'Хамовники Пшеничное': ('4.8', '230rub'), 'Einsiedler Weissbier': ('5.2', '284rub'), 'Weihenstephaner Hefe-Weissbier': ('5.4', '288rub'), 'Erdinger Weissbier': ('5.3', '295rub'), 'Limburgse Witte': ('5.0', '315rub'), 'Schneider TAP4 Meine Festweisse': ('6.2', '340rub'), 'Van Steenberge Baptist Wit': ('5.0', '365rub'), 'Hoegaarden': ('4.8', '368rub'), 'Mort Subite Witte': ('5.5', '370rub'), 'Ayinger Urweisse': ('5.8', '390rub'), 'Медовуха': ('6.5', '178rub'), 'Schöfferhofer Grapefruit ': ('2.5', '275rub'), 'Mort SubiteKriek': ('4.3', '370rub'), 'Kriek Boon Lambic': ('4.0', '375rub'), 'Bockor Kriek Max': ('3.5', '415rub'), 'Barbe Ruby': ('7.7', '430rub'), 'Huyghe Delirium Red ': ('8.5', '460rub'), 'Lindemans Pecheresse': ('2.5', '525rub'), 'Пятый Океан IPA': ('4.5', '184rub'), 'Panzer Mikhail ': ('4.7', '205rub'), 'Beer Bros Brewery Smart Admin(APA)': ('5.5', '235rub'), 'Konix IPA Overfall': ('6.5', '255rub'), 'XP Brewery Minimax(APA)': ('5.0', '256rub'), 'XP Brewery Hyperplane': ('7.5', '268rub'), 'Panzer Starlight(APA)': ('5.4', '270rub'), 'Landau Beerlab Тотальное обнуление(West coast IPA)': ('7.0', '280rub'), 'Beer Bros Mango Mayhem(IPA)': ('6.8', '285rub'), 'Black Head WTF(APA)': ('5.5', '285rub'), 'Plan B Солнечный ветер(APA)': ('4.8', '290rub'), 'Волковская Пивоварня Sliva': ('4.8', '295rub'), 'Chibis Avenue 77 Simcoe & ampMosaic(American IPA)': ('6.6', '300rub'), 'Konix Milk Shake Peach':('6.0', '300rub'), 'Beer Bros Heavy Gratefulness (DIPA)': ('8.3', '305rub'), 'Panzer Акварель (IPA)': ('7.2', '310rub'), 'PanzerSuper Mango(APA)': ('5.4', '310rub'), "Salden'S MilkShake Coconut & ampIce-Cream Dipa": ('8.0', '315rub'), 'Landau Beerlab Sabro Lake': ('7.0', '315rub'), "Salden'S MilkShake Mango DIPA": ('8.0', '315rub'), 'Plan B Отличный План': ('7.3', '325rub'), 'PivotPoint БАНАНБЕRRИ Apricot(Milkshake IPA)': ('6.7', '330rub'), 'Plan B Ковбой Мальборо': ('6.5', '334rub'), 'Alaska Метаморфозы(Milkshake Fruit DIPA)': ('7.0', '335rub'), 'Black Head Крепкая Парочка(DIPA)': ('8.0', '335rub'), 'Coven Aura ': ('6.5', '335rub'), 'Бакунин Fibonacci(DIPA)': ('8.0', '340rub'), 'Plan B Tropical Painkiller': ('8.5', '345rub'), "Palchevskiy&amp; Wolf's Crossover(DIPA)": ('6.5', '345rub'), 'Af Brew Mosaic (IPA)': ('6.7', '350rub'), 'Joker IPA': ('5.0', '355rub'), 'Af Brew Ingria (IPA)': ('5.8', '360rub'), 'Pivot Point Ёлы-Палы (Triple IPA)': ('11.2', '360rub'), 'Brewdog Hazy Jane 5.0': ('5.0', '405rub'), 'Brewdog Duopolis': ('4.7', '405rub'), 'Kona Big Wave Golden Ale': ('4.4', '415rub'), 'Mikkeller Side Eyes Pale Ale': ('4.6', '425rub'), 'Brewdog Dead Pony Club': ('3.8', '425rub'), 'Jaws Populism Mosaic Edition (NEIPA)': ('6.0', '425rub'), 'Brewdog Elvis Juice':
        ('6.5', '445rub'), 'Sweet Water IPA ': ('6.3', '486rub'), 'Sweet Water 420 Strain G13 (New England IPA)': ('6.0', '530rub'), 'Pivot Point Белка, Я Люблю Тебя': ('6.5', '280rub'), 'G&amp; B Вишня в Шоколаде (Stout)': ('6.0', '285rub'), 'Konix Black Illusion (Milk Stout)': ('6.0', '300rub'), "Salden'S Sweet Stout Cola": ('6.5', '305rub'), 'Alaska Стаутский Советник': ('8.5', '320rub'),
        'Selfmade Cocoa Chaos (Imperial Stout)': ('8.4', '325rub'), 'Trigger RIS': ('9.5', '365rub'), 'XP Brewery Tetrahymena (English Barleywine)': ('13.0', '375rub'), 'XP Brewery MindBug (RIS)': ('11.0', '375rub'), 'Konix RIS Barrel # Виски': ('12.5', '405rub'), 'Jaws Holiness (Quadrupel)': ('9.0', '420rub'), 'Af Brew Popcorn Pimp (Imperial Stout)': ('10.0', '465rub'), 'Atmosphere Тропическая Дичь 2.0 Pineapple&amp; Passion Fruit Sour Ale': ('5.5', '280rub'), 'XP Brewery Mango&amp; Raspberry': ('6.5', '283rub'), 'Coven Last Resort (Tomato Gose)': ('6.5', '290rub'), 'Landau Beerlab Hard Seltzer Lemon &amp; Lime (Sour Ale)': ('5.5', '295rub'), 'L&amp; K Pizza Gose': ('5.2', '300rub'), 'LaBEERint Sour Kiwi Pinapple': ('4.0', '310rub'), 'Brewlok Rusalka Raspberry Sour Ale': ('5.0', '310rub'), 'Panzer Catch Up! Tomato Gose': ('4.3', '315rub'), 'Atmosphere Exotic': ('8.0', '320rub'), 'Alaska Фейхоа (Sour Ale)': ('5.5', '335rub'), 'Zavod Bloody Mary v2.0 (Gose)': ('4.2', '335rub'), "Salden'S Tomato Gose": ('5.0', '335rub'), 'Jaws Berry Mary Cranberry (Berliner Weisse)': ('3.8', '370rub'), 'Бакунин Funky Fresh': ('5.0', '370rub'), 'Jaws Sour Breeze Mango':
        ('4.5', '380rub'), 'Big Village Hyperrealism (Imperial Gose)': ('10.0', '385rub'), 'Af Brew Raspberry is my Sanctuary (Berliner Weisse)': ('5.3', '390rub'), 'Af Brew Kiss the Dust! DDH Citra+Mosaic (Sour IPA)': ('8.0', '450rub'), "Af Brew It's Over 9000 Mango/Pineapple/Lime ": ('7.0', '455rub'), "Af Brew It's Over 9000! Raspberry/Cherry/Lime": ('7.0', '455rub'), 'Jaws Ищу Человека White Edition': ('5.5', '550rub'), 'XP Brewery Average Bear': ('5.0', '248rub'), 'St.Anton Сидр п/сух.': ('5.0', '254rub'), 'Trigger Сидр вишневый полусухой': ('4.5', '265rub'), 'Coven Ich Will (Hoppy Lager)': ('5.5', '270rub'), 'Brewlok Kikimora (Milk Stout)': ('6.5', '280rub'), 'Konix Very Happy Cider': ('5.8', '285rub'), 'Konix Hefeweizen Banana ': ('4.5', '290rub'), 'Волковская Пивоварня Hoppy Cider': ('4.5', '290rub'), 'Plan B Бэрримор Овсяный Стаут': ('6.5', '295rub'), 'Brewlok Koshey (Pepper Stout)': ('6.9', '310rub'), 'Trigger Сидр Aperol Spritz': ('4.5', '315rub'), 'N.Rigas White Moon (Stout)': ('5.5', '315rub'), 'Бакунин Рука Бога (Uncommon Golden Ale)': ('4.5', '315rub'), 'Wychwood Hobgoblin Gold': ('4.2', '320rub'), 'Бакунин Нуар': ('4.5', '330rub'), 'Konix Brewery Cherry Ruby (Fruit Beer)': ('7.0', '355rub'), 'Brewdog Pale Ale': ('4.2', '375rub'), 'Af Brew Redneck Ale (Pumpkin Ale)': ('7.0', '385rub'), 'Сидр Келвиш': ('4.7', '178rub'), "Lilley's Cider Mango": ('4.0', '350rub'), "Lilley's Cider Cherries &amp; Berries": ('4.0', '350rub'), 'Alska Strawberry&amp; Lime ': ('4.0', '370rub'), 'Cidre Celtic Marches Abrahalls AD': ('6.0', '375rub'), 'Вятский Квас': ('0.0', '75rub'), 'Лимонад Бочкари': ('0.0', '85rub')
}


